#!/bin/env python3
# Generate a Gen5 GEMV/GEMM kernel by unrolling the proven gemv_n32 pattern.
#
#   gen_gemv.py N              -> single-token GEMV: out(d) = W(d,N) @ x(N)
#   gen_gemv.py N T D          -> multi-token, thread loops T (streams W/token)
#   gen_gemv.py N pack RPAD    -> token-in-index GEMM (prefill, latency-hiding)
#
# pack mode: ONE thread computes ONE token's 8 output rows. The dispatch
# launches T*RPAD threads (RPAD = D/8 padded up to a power of two); each
# thread derives token = index>>log2(RPAD) and row_block = index&(RPAD-1)
# from its inline index — no division. This multiplies the in-flight thread
# count by T, hiding the OWord-read latency that starves the 36-thread
# single GEMV. Padding rows (row_block >= D/8) compute garbage into the
# per-token output padding and are ignored on readback.
#   bti[0]=W (row-major), bti[1]=X (token t at byte t*N*4),
#   bti[2]=OUT (token t at byte t*RPAD*8*4; valid rows 0..D-1).
import sys, math

N = int(sys.argv[1]) if len(sys.argv) > 1 else 256
PACK = len(sys.argv) > 2 and sys.argv[2] == "pack"
if PACK:
    RPAD = int(sys.argv[3])
    T = 0
    D = 0
else:
    T = int(sys.argv[2]) if len(sys.argv) > 2 else 1
    D = int(sys.argv[3]) if len(sys.argv) > 3 else 0
ROWS = 8
assert N % 8 == 0, "N must be a multiple of 8 (SIMD8 chunks)"
CHUNKS = N // 8
ROWBYTES = N * 4
BLOCKBYTES = ROWS * ROWBYTES
XSTRIDE = N * 4

XBASE = 10
WBASE = XBASE + CHUNKS
ACC = WBASE + 1
TMP = ACC + 1
HS = TMP + 1
PACKR = HS + 2

out = []
def e(s): out.append(s)


def emit_rows_and_hsum():
    for r in range(ROWS):
        e("add (1)  g6<1>UD    g5<0,1,0>UD      %dUD               { align1 };" % (r * ROWBYTES))
        for c in range(CHUNKS):
            e("add (1)  g3.8<1>UD  g6<0,1,0>UD      0x%xUD             { align1 };" % (c * 32))
            e("send (16) 0 g%d<1>UW g3<8,8,1>UW read(0,0,2,0) mlen 1 rlen 1 { align1 };" % WBASE)
            if c == 0:
                e("mul (8)  g%d<1>F    g%d<8,8,1>F      g%d<8,8,1>F        { align1 };" % (ACC, WBASE, XBASE))
            else:
                e("mul (8)  g%d<1>F    g%d<8,8,1>F      g%d<8,8,1>F        { align1 };" % (TMP, WBASE, XBASE + c))
                e("add (8)  g%d<1>F    g%d<8,8,1>F      g%d<8,8,1>F        { align1 };" % (ACC, ACC, TMP))
        e("add (4)  g%d<1>F    g%d.0<4,4,1>F    g%d.16<4,4,1>F     { align1 };" % (HS, ACC, ACC))
        e("add (2)  g%d<1>F    g%d.0<2,2,1>F    g%d.8<2,2,1>F      { align1 };" % (HS, HS, HS))
        e("add (1)  g%d.%d<1>F  g%d.0<0,1,0>F    g%d.4<0,1,0>F      { align1 };" % (PACKR, r * 4, HS, HS))


if PACK:
    SHIFT = int(math.log2(RPAD))
    MASK = RPAD - 1
    OUTSTRIDE = RPAD * ROWS * 4
    tag = "n%d_pack%d" % (N, RPAD)
    e("// AUTO-GENERATED by gen_gemv.py — token-in-index. N=%d RPAD=%d." % (N, RPAD))
    e("mov (8)  g3<1>UD    g0<8,8,1>UD                         { align1 };")
    e("mov (8)  g4<1>UD    g0<8,8,1>UD                         { align1 };")
    e("and (1)  g2<1>UD    g1<0,1,0>UD      0x%xUD             { align1 };  // row_block = idx & %d" % (MASK, MASK))
    e("shr (1)  g9<1>UD    g1<0,1,0>UD      %dUD               { align1 };  // token = idx >> %d" % (SHIFT, SHIFT))
    e("mul (1)  g5<1>UD    g2<0,1,0>UD      %dUD               { align1 };  // W base = row_block*%d" % (BLOCKBYTES, BLOCKBYTES))
    e("mul (1)  g8<1>UD    g9<0,1,0>UD      %dUD               { align1 };  // x base = token*%d" % (XSTRIDE, XSTRIDE))
    e("mul (1)  g7<1>UD    g9<0,1,0>UD      %dUD               { align1 };  // out base = token*%d ..." % (OUTSTRIDE, OUTSTRIDE))
    e("mul (1)  g11<1>UD   g2<0,1,0>UD      32UD               { align1 };")
    e("add (1)  g7<1>UD    g7<0,1,0>UD      g11<0,1,0>UD       { align1 };  // ... + row_block*32")
    e("// ---- read x[token] (%d chunks) into g%d..g%d ----" % (CHUNKS, XBASE, XBASE + CHUNKS - 1))
    for c in range(CHUNKS):
        e("add (1)  g4.8<1>UD  g8<0,1,0>UD      0x%xUD             { align1 };" % (c * 32))
        e("send (16) 0  g%d<1>UW  g4<8,8,1>UW  read(1, 0, 2, 0) mlen 1 rlen 1 { align1 };" % (XBASE + c))
    emit_rows_and_hsum()
    e("// ---- write this token's 8 rows at out base ----")
    e("mov (1)  g3.8<1>UD  g7<0,1,0>UD                         { align1 };")
    e("mov (8)  m1<1>F     g%d<8,8,1>F                         { align1 };" % PACKR)
    e("send (16) 0 acc0<1>UW g3<8,8,1>UW write(2, 2, 0, 0) mlen 2 rlen 0 { align1 };")
    e("send (16) 0 acc0<1>UW g0<8,8,1>UW")
    e("\tthread_spawner(0, 0, 0) mlen 1 rlen 0 { align1 EOT };")
else:
    OUTSTRIDE = D * 4
    tag = "n%d" % N if T <= 1 else "n%d_t%d" % (N, T)
    e("// AUTO-GENERATED by gen_gemv.py — do not edit. N=%d T=%d D=%d." % (N, T, D))
    e("mov (8)  g3<1>UD    g0<8,8,1>UD                         { align1 };")
    e("mov (8)  g4<1>UD    g0<8,8,1>UD                         { align1 };")
    e("and (1)  g2<1>UD    g1<0,1,0>UD      0x3ffUD            { align1 };")
    e("mul (1)  g5<1>UD    g2<0,1,0>UD      %dUD               { align1 };" % BLOCKBYTES)
    e("mul (1)  g7<1>UD    g2<0,1,0>UD      32UD               { align1 };")
    for tok in range(max(T, 1)):
        e("// ================= token %d =================" % tok)
        for c in range(CHUNKS):
            e("mov (1)  g4.8<1>UD  0x%xUD                              { align1 };" % (tok * XSTRIDE + c * 32))
            e("send (16) 0  g%d<1>UW  g4<8,8,1>UW  read(1, 0, 2, 0) mlen 1 rlen 1 { align1 };" % (XBASE + c))
        emit_rows_and_hsum()
        e("add (1)  g3.8<1>UD  g7<0,1,0>UD      0x%xUD             { align1 };" % (tok * OUTSTRIDE))
        e("mov (8)  m1<1>F     g%d<8,8,1>F                         { align1 };" % PACKR)
        e("send (16) 0 acc0<1>UW g3<8,8,1>UW write(2, 2, 0, 0) mlen 2 rlen 0 { align1 };")
    e("send (16) 0 acc0<1>UW g0<8,8,1>UW")
    e("\tthread_spawner(0, 0, 0) mlen 1 rlen 0 { align1 EOT };")

txt = "\n".join(out) + "\n"
fn = "gemv_%s.g4a" % tag
open(fn, "w").write(txt)
print("wrote %s: %d lines, ~%d instructions, GRF top=%d"
      % (fn, len(out), len([x for x in out if not x.startswith('//')]), PACKR))
