#!/bin/env python3
# Generate a Gen5 GEMV kernel (out[i] = dot(W[i][0..N-1], x[0..N-1]))
# by unrolling the proven gemv_n32 pattern to arbitrary N. Surface x is
# read ONCE per thread (into a register block) and reused across all
# ROWS_PER_THREAD output rows, so the only redundancy is per-thread, not
# per-row. No loops, no a0 addressing — the same low-risk structure that
# assembled and ran bit-exact first try at N=32.
#
# Binding table: [0]=W (DxN fp32), [1]=x (N fp32), [2]=out (D fp32).
# Inline thread index at g1.0. 8 output rows per thread, written as 8
# fp32 (2 OWords) like saxpy.
import sys

N = int(sys.argv[1]) if len(sys.argv) > 1 else 256
ROWS = 8
assert N % 8 == 0, "N must be a multiple of 8 (SIMD8 chunks)"
CHUNKS = N // 8            # 8 fp32 per chunk
ROWBYTES = N * 4           # bytes per W row
BLOCKBYTES = ROWS * ROWBYTES  # bytes per thread's row-block

# GRF map: x chunks live in g10..g(10+CHUNKS-1). W scratch reuses a small
# window above x. acc/hsum/pack are placed above the x block.
XBASE = 10
WBASE = XBASE + CHUNKS        # first W scratch GRF
ACC = WBASE + 1
TMP = ACC + 1
HS = TMP + 1
PACK = HS + 2                 # output pack GRF (8 fp32)

out = []
def e(s): out.append(s)

e("// AUTO-GENERATED by gen_gemv.py — do not edit. N=%d, ROWS=%d." % (N, ROWS))
e("mov (8)  g3<1>UD    g0<8,8,1>UD                         { align1 };")
e("mov (8)  g4<1>UD    g0<8,8,1>UD                         { align1 };")
e("and (1)  g2<1>UD    g1<0,1,0>UD      0x3ffUD            { align1 };")
e("mul (1)  g5<1>UD    g2<0,1,0>UD      %dUD               { align1 };  // W block base = t*%d" % (BLOCKBYTES, BLOCKBYTES))

e("// ---- read shared x (%d chunks of 8 fp32) into g%d..g%d ----" % (CHUNKS, XBASE, XBASE + CHUNKS - 1))
for c in range(CHUNKS):
    e("mov (1)  g4.8<1>UD  0x%xUD                              { align1 };" % (c * 32))
    e("send (16) 0  g%d<1>UW  g4<8,8,1>UW  read(1, 0, 2, 0) mlen 1 rlen 1 { align1 };" % (XBASE + c))

for r in range(ROWS):
    e("// ---- row %d ----" % r)
    e("add (1)  g6<1>UD    g5<0,1,0>UD      %dUD               { align1 };  // W row base" % (r * ROWBYTES))
    for c in range(CHUNKS):
        e("add (1)  g3.8<1>UD  g6<0,1,0>UD      0x%xUD             { align1 };" % (c * 32))
        e("send (16) 0 g%d<1>UW g3<8,8,1>UW read(0,0,2,0) mlen 1 rlen 1 { align1 };" % WBASE)
        if c == 0:
            e("mul (8)  g%d<1>F    g%d<8,8,1>F      g%d<8,8,1>F        { align1 };" % (ACC, WBASE, XBASE))
        else:
            e("mul (8)  g%d<1>F    g%d<8,8,1>F      g%d<8,8,1>F        { align1 };" % (TMP, WBASE, XBASE + c))
            e("add (8)  g%d<1>F    g%d<8,8,1>F      g%d<8,8,1>F        { align1 };" % (ACC, ACC, TMP))
    # horizontal sum of the 8 SIMD lanes -> scalar into PACK float-lane r
    e("add (4)  g%d<1>F    g%d.0<4,4,1>F    g%d.16<4,4,1>F     { align1 };" % (HS, ACC, ACC))
    e("add (2)  g%d<1>F    g%d.0<2,2,1>F    g%d.8<2,2,1>F      { align1 };" % (HS, HS, HS))
    e("add (1)  g%d.%d<1>F  g%d.0<0,1,0>F    g%d.4<0,1,0>F      { align1 };" % (PACK, r * 4, HS, HS))

e("// ---- write 8 output rows (8 fp32 = 2 OWords) ----")
e("mul (1)  g3.8<1>UD  g2<0,1,0>UD      32UD               { align1 };")
e("mov (8)  m1<1>F     g%d<8,8,1>F                         { align1 };" % PACK)
e("send (16) 0 acc0<1>UW g3<8,8,1>UW write(2, 2, 0, 0) mlen 2 rlen 0 { align1 };")
e("send (16) 0 acc0<1>UW g0<8,8,1>UW")
e("\tthread_spawner(0, 0, 0) mlen 1 rlen 0 { align1 EOT };")

txt = "\n".join(out) + "\n"
open("gemv_n%d.g4a" % N, "w").write(txt)
print("wrote gemv_n%d.g4a: %d lines, ~%d instructions, GRF top=%d"
      % (N, len(out), len(out) - 4, PACK))
