#!/bin/env python3
# Generate a Gen5 GEMV/GEMM kernel by unrolling the proven gemv_n32 pattern.
#
#   gen_gemv.py N            -> single-token GEMV: out(d) = W(d,N) @ x(N)
#   gen_gemv.py N T D        -> multi-token GEMM: OUT(d,T) = W(d,N) @ X(N,T)
#
# Multi-token (prefill) mode: thread `index` owns 8 consecutive output rows
# and computes them for ALL T token-columns in ONE dispatch, streaming its
# W rows once per token. This does NOT reuse W across tokens (no register
# tiling) but it collapses T per-token dispatches into one, amortizing the
# ~1.3ms fixed Gen5 dispatch cost over T tokens — the prefill lever.
#
# Binding table: [0]=W (D x N fp32, row-major), [1]=X (N x T, token-major:
# token t's vector at byte t*N*4), [2]=OUT (D x T, token-major: token t at
# byte t*D*4). Inline thread index (row-block) at g1.0.
import sys

N = int(sys.argv[1]) if len(sys.argv) > 1 else 256
T = int(sys.argv[2]) if len(sys.argv) > 2 else 1     # token columns
D = int(sys.argv[3]) if len(sys.argv) > 3 else 0     # total out rows (for stride)
ROWS = 8
assert N % 8 == 0, "N must be a multiple of 8 (SIMD8 chunks)"
CHUNKS = N // 8
ROWBYTES = N * 4
BLOCKBYTES = ROWS * ROWBYTES
XSTRIDE = N * 4                # bytes between successive token x-vectors
OUTSTRIDE = D * 4              # bytes between successive token output columns

XBASE = 10
WBASE = XBASE + CHUNKS
ACC = WBASE + 1
TMP = ACC + 1
HS = TMP + 1
PACK = HS + 2

out = []
def e(s): out.append(s)

tag = "n%d" % N if T <= 1 else "n%d_t%d" % (N, T)
e("// AUTO-GENERATED by gen_gemv.py — do not edit. N=%d T=%d D=%d." % (N, T, D))
e("mov (8)  g3<1>UD    g0<8,8,1>UD                         { align1 };")
e("mov (8)  g4<1>UD    g0<8,8,1>UD                         { align1 };")
e("and (1)  g2<1>UD    g1<0,1,0>UD      0x3ffUD            { align1 };")
e("mul (1)  g5<1>UD    g2<0,1,0>UD      %dUD               { align1 };  // W block base = t*%d" % (BLOCKBYTES, BLOCKBYTES))
e("mul (1)  g7<1>UD    g2<0,1,0>UD      32UD               { align1 };  // out row base = t*32")

for tok in range(max(T, 1)):
    e("// ================= token %d =================" % tok)
    e("// ---- read x[token %d] (%d chunks) into g%d..g%d ----" % (tok, CHUNKS, XBASE, XBASE + CHUNKS - 1))
    for c in range(CHUNKS):
        e("mov (1)  g4.8<1>UD  0x%xUD                              { align1 };" % (tok * XSTRIDE + c * 32))
        e("send (16) 0  g%d<1>UW  g4<8,8,1>UW  read(1, 0, 2, 0) mlen 1 rlen 1 { align1 };" % (XBASE + c))
    for r in range(ROWS):
        e("add (1)  g6<1>UD    g5<0,1,0>UD      %dUD               { align1 };" % (r * ROWBYTES))
        for c in range(CHUNKS):
            e("add (1)  g3.8<1>UD  g6<0,1,0>UD      0x%xUD             { align1 };" % (c * 32))
            e("send (16) 0 g%d<1>UW g3<8,8,1>UW read(0,0,2,0) mlen 1 rlen 1 { align1 };" % WBASE)
            if c == 0:
                e("mul (8)  g%d<1>F    g%d<8,8,1>F      g%d<8,8,1>F        { align1 };" % (ACC, WBASE, XBASE))
            else:
                e("mul (8)  g%d<1>F    g%d<8,8,1>F      g%d<8,8,1>F        { align1 };" % (TMP, WBASE, XBASE + c))
                e("add (8)  g%d<1>F    g%d<8,8,1>F      g%d<8,8,1>F        { align1 };" % (ACC, ACC, TMP))
        e("add (4)  g%d<1>F    g%d.0<4,4,1>F    g%d.16<4,4,1>F     { align1 };" % (HS, ACC, ACC))
        e("add (2)  g%d<1>F    g%d.0<2,2,1>F    g%d.8<2,2,1>F      { align1 };" % (HS, HS, HS))
        e("add (1)  g%d.%d<1>F  g%d.0<0,1,0>F    g%d.4<0,1,0>F      { align1 };" % (PACK, r * 4, HS, HS))
    e("// ---- write token %d's 8 rows at t*32 + %d ----" % (tok, tok * OUTSTRIDE))
    e("add (1)  g3.8<1>UD  g7<0,1,0>UD      0x%xUD             { align1 };" % (tok * OUTSTRIDE))
    e("mov (8)  m1<1>F     g%d<8,8,1>F                         { align1 };" % PACK)
    e("send (16) 0 acc0<1>UW g3<8,8,1>UW write(2, 2, 0, 0) mlen 2 rlen 0 { align1 };")

e("send (16) 0 acc0<1>UW g0<8,8,1>UW")
e("\tthread_spawner(0, 0, 0) mlen 1 rlen 0 { align1 EOT };")

txt = "\n".join(out) + "\n"
fn = "gemv_%s.g4a" % tag
open(fn, "w").write(txt)
print("wrote %s: %d lines, ~%d instructions, GRF top=%d, T=%d"
      % (fn, len(out), len(out) - 5, PACK, T))
